import pandas as pd

data=pd.Series([5,4,-1,3,7],index=["a","b","c","d","e"])
print("資料型態：", data.dtype)
print("資料數量：", data.size)
print("資料索引：", data.index)
print("第二筆資料：", data[1])
print("索引 e 的資料：", data["e"])
print("總和：", data.sum())
print("最大值：", data.max())
print("乘法總和：", data.prod())
print("平均數：", data.mean())
print("中位數：", data.median())
print("標準差：", data.std())
print("最大的兩個數：", data.nlargest(2))
print("最小的兩個數：", data.nsmallest(2))

data2=pd.Series(["您好", "Python", "Pandas"])
print("全部變小寫：", data2.str.lower())
print("全部變大寫：", data2.str.upper())
print("計算每個字串長度：", data2.str.len())
print("串成一個字串：", data2.str.cat(sep=","))
print("判斷字串是否包含大寫 P：", data2.str.contains("P"))
print("把您好取代成 Hello：", data2.str.replace("您好", "Hello"))